SELECT
    CASE
        WHEN SUBSTR(PRICE, 0, LENGTH(PRICE) - 4) = ''  THEN '0'
        ELSE CONCAT(SUBSTR(PRICE, 0, LENGTH(PRICE) - 4), '0000')
    END AS PRICE_GROUP, 
    COUNT(PRODUCT_ID) AS PRODUCTS
FROM
    PRODUCT
GROUP BY
    SUBSTR(PRICE, 0, LENGTH(PRICE) - 4)
ORDER BY
    SUBSTR(PRICE, 0, LENGTH(PRICE) - 4)


