SELECT CAR_ID, MAX(AVAILABILITY) AS AVAILABILITY
FROM (
    SELECT
        CAR_ID,
        CASE WHEN
            START_DATE <= DATE_FORMAT('20221016','%Y%m%d')
            AND END_DATE >= DATE_FORMAT('20221016','%Y%m%d')
            THEN '대여중'
            ELSE '대여 가능' END AS "AVAILABILITY",
        START_DATE,
        END_DATE
    FROM CAR_RENTAL_COMPANY_RENTAL_HISTORY
)A 
GROUP BY CAR_ID
ORDER BY CAR_ID DESC