SELECT
    CAR_ID,
    ROUND(AVG(DATEDIFF(end_date, start_date) + 1), 1) AS AVERAGE_DURATION
FROM
    CAR_RENTAL_COMPANY_RENTAL_HISTORY
GROUP BY
    CAR_ID
HAVING
    AVG(DATEDIFF(end_date, start_date) + 1) >= 7
ORDER BY
    AVERAGE_DURATION DESC,
    CAR_ID DESC
